apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    k8s-app: alertmanager
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: alertmanager
  template:
    metadata:
      labels:
        k8s-app: alertmanager
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus-alertmanager
        image: prom/alertmanager:v0.15.0
        args:
          - '--config.file=/etc/config/alertmanager.yml'
          - '--storage.path=/data'
          - '--web.external-url=/'
        ports:
        - containerPort: 9093
        readinessProbe:
          httpGet:
            path: /#/status
            port: 9093
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: templates-volume
          mountPath: /alertmanager/template/
        - name: storage-volume
          mountPath: "/data"
          subPath: ""
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: templates-volume
        configMap:
          name: alertmanager-templates
      - name: storage-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  selector:
    k8s-app: alertmanager
  type: NodePort
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093
